import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { db } from "@/lib/db";

export async function GET(req: Request) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return new Response("Unauthorized", { status: 401 });
  }

  const url = new URL(req.url);
  const entityId = url.searchParams.get("entityId");
  const format = url.searchParams.get("format") ?? "html";

  if (!entityId) {
    return Response.json({ error: "Missing entityId" }, { status: 400 });
  }

  const entity = await db.gameEntity.findFirst({
    where: { id: entityId, game: { ownerId: session.user.id } },
    include: {
      game: true,
      briefVersions: { orderBy: { version: "desc" }, take: 1 },
      relationshipsFrom: { include: { toEntity: true } },
      relationshipsTo: { include: { fromEntity: true } },
    },
  });

  if (!entity) {
    return Response.json({ error: "Entity not found" }, { status: 404 });
  }

  const brief = entity.briefVersions[0];
  if (!brief) {
    return Response.json({ error: "No brief generated" }, { status: 404 });
  }

  const sections = [
    { title: "Backstory", content: brief.backstory },
    { title: "Personality", content: brief.personality },
    { title: "Public Goals", content: brief.goalsPublic },
    { title: "Secret Goals", content: brief.goalsSecret },
    { title: "Relationships", content: brief.relationships },
    { title: "Mechanics", content: brief.mechanics },
    { title: "Contacts", content: brief.contacts },
  ].filter((s) => s.content);

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${entity.name} — Character Brief</title>
  <style>
    body {
      font-family: 'Georgia', serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
      color: #1a1a1a;
      line-height: 1.6;
    }
    .header {
      border-bottom: 3px double #333;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .game-title {
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 2px;
      color: #666;
      margin-bottom: 4px;
    }
    h1 {
      font-size: 28px;
      margin: 0 0 8px;
    }
    .meta {
      font-size: 14px;
      color: #666;
    }
    .meta span {
      margin-right: 16px;
    }
    h2 {
      font-size: 18px;
      margin-top: 28px;
      margin-bottom: 12px;
      padding-bottom: 4px;
      border-bottom: 1px solid #ddd;
    }
    p {
      margin-bottom: 12px;
    }
    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #ddd;
      font-size: 11px;
      color: #999;
    }
    @media print {
      body { padding: 20px; }
      h2 { page-break-after: avoid; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="game-title">${entity.game.name}${entity.game.genre ? ` — ${entity.game.genre}` : ""}</div>
    <h1>${entity.name}</h1>
    <div class="meta">
      ${entity.faction ? `<span>Faction: <strong>${entity.faction}</strong></span>` : ""}
      ${entity.archetype ? `<span>Archetype: <strong>${entity.archetype}</strong></span>` : ""}
      <span>Brief v${brief.version} (${brief.status})</span>
    </div>
  </div>

  ${sections.map((s) => `<h2>${s.title}</h2>\n${s.content!.split("\n").map((p) => `<p>${p}</p>`).join("\n")}`).join("\n\n")}

  <div class="footer">
    Generated by LARP Forge · ${new Date().toLocaleDateString()}
  </div>
</body>
</html>`;

  if (format === "html") {
    return new Response(html, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `attachment; filename="${entity.name.replace(/[^a-zA-Zа-яА-Я0-9]/g, "_")}_brief.html"`,
      },
    });
  }

  // For PDF, return the HTML content which the client can use with browser print
  return new Response(html, {
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}
